import type { Metadata } from "next";
import { Geist, Geist_Mono, Lexend, Poppins } from "next/font/google";
import "./globals.css";
import './designsystems/index.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const lexend = Lexend({
  subsets: ['latin'],
  weight: ['300', '400', '600'],
  variable: '--font-lexend',
  display: 'swap',
})

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['600', '700'],
  variable: '--font-poppins',
  display: 'swap',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${lexend.variable} ${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
